language: android
jdk: oraclejdk8

notifications:
  webhooks: "https://hooks.slack.com/services/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"

branches:
  only:
    - master

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew clean build

deploy:
  provider: pre-release
  file_glob: true
  file: app/build/outputs/apk/*.apk
  skip_cleanup: true

  on:
    repo: T-Jedsada/Dagger2_MVP_Example
    jdk: oraclejdk8
  api_key:
    secure: ${personal_token}